import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MobileLayout from "@/components/MobileLayout";
import DesktopLayout from "@/components/DesktopLayout";

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Black.otf",
    },
    {
      path: "../public/fonts/Satoshi-Bold.otf",
    },
    {
      path: "../public/fonts/Satoshi-Light.otf",
    },
    {
      path: "../public/fonts/Satoshi-Medium.otf",
    },
    {
      path: "../public/fonts/Satoshi-Regular.otf",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${satoshi.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <MobileLayout>{children}</MobileLayout>
        <DesktopLayout>{children}</DesktopLayout>
      </body>
    </html>
  );
}
